#include <stdio.h>
#define DSM_CACHE_LINE_WIDTH (12) 
#define DSM_CACHE_LINE_SIZE (1u << DSM_CACHE_LINE_WIDTH)
enum RawMessageType{
  R_READ_MISS = 1,
  R_WRITE_MISS = 2,
  R_WRITE_SHARED = 3,
  R_EVICT_SHARED,
  R_EVICT_DIRTY,
  DIR_2_APP_READ_MISS_ACKDATA = 11, 
  DIR_2_APP_WRITE_MISS_ACKDATA,
  DIR_2_APP_WRITE_MISS_SHAREDDATA,
  DIR_2_APP_WRITE_SHARED_ONLYACK,
  DIR_2_APP_EVICT_SHARED_ACK,
  DIR_2_APP_EVICT_DIRTY_ACK,
  DIR_2_APP_M_CHECK_FAIL,
  DIR_2_APP_BITMAP_CHECK_FAIL,
  DIR_2_AGENT_READ_MISS_DIRTY = 21,
  DIR_2_AGENT_WRITE_MISS_DIRTY,
  DIR_2_AGENT_WRITE_MISS_SHARED,
  DIR_2_AGENT_WRITE_SHARED_NOTONLY,
  AGENT_2_DIR_READ_MISS_DIRTY_ACKDATA=31,
  AGENT_2_DIR_WRITE_MISS_DIRTY_ACK,
  AGENT_2_DIR_WRITE_MISS_SHARED_ACK,
  AGENT_2_DIR_WRITE_SHARED_NOTONLY_ACK,
  AGENT_2_DIR_M_CHECK_FAIL,
  AGENT_2_APP_READ_MISS_DIRTY_ACKDATA=41,
  AGENT_2_APP_WRITE_MISS_DIRTY_ACKDATA,
  DIR_2_APP_WRITE_MISS_SHARED_AGGACK_ACK=51,
  DIR_2_APP_WRITE_SHARED_NOTONLY_AGGACK_ACK,
  INIT_DIR,
  INIT_NET,
};
enum RawState{
  S_UNSHARED = 0,
  S_SHARED = 1,
  S_DIRTY = 2,
  S_TO_UNSHARED,
  S_TO_SHARED,
  S_TO_DIRTY,
};
enum CacheStatus{
  INVALID = 0,
  SHARED = 1,
  MODIFIED,
  TO_INVALID,
  TO_SHARED,
  TO_MODIFIED,
};